Upgrade to paperless-ngx v1.7.0
TheBestMoshe/home-assistant-addons pull request #20
Opened 2022-04-28 02:06 UTC by axyjo

Tested on aarch64 + amd64

2022-04-28 14:41 UTC, TheBestMoshe commented
Thanks for the PR.

[This version](https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.7.0) has a breaking change:

> `PAPERLESS_URL` is now required when using a reverse proxy. See https://github.com/paperless-ngx/paperless-ngx/pull/674.

I believe we need to expose this variable to the Home Assitant config panel so that users can use this addon with a reverse proxy.

2022-05-28 10:26 UTC, tux2000 commented
This would be great to get on the main branch 🙂

2022-06-16 17:26 UTC, axyjo commented
@TheBestMoshe please take a look?

2022-06-20 14:27 UTC, TheBestMoshe requested changes

2022-06-20 14:27 UTC, TheBestMoshe commented on paperless-ngx/scripts/docker-entrypoint.sh
> +export PAPERLESS_URL=$(jq --raw-output ".url" $CONFIG_PATH)
When running `docker run -p 8000:8000 -v $PWD/paperless-ngx/data:/data local/paperless-ngx` without setting the url option it throws an error:

```
ERRORS:
?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found null. See the release notes for details.
Search index out of date. Updating...
SystemCheckError: System check identified some issues:

ERRORS:
?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found null. See the release notes for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user
```

This error is caused by the fact that Django now requires the `CSRF_TRUSTED_ORIGINS` to be set or left as an empty string. Since the default value, you set in the config is null, this sets `PAPERLESS_URL` to `null` which sets `CSRF_TRUSTED_ORIGINS` to null.

To fix this, if the `url` in the config is set to null, we can set the `PAPERLESS_URL` to an empty string:

```bash
export PAPERLESS_URL=$(jq --raw-output ".url // ''" $CONFIG_PATH)
```

2022-07-07 14:16 UTC, elahd commented
@axyjo Any chance you'll be able to make this change?

2022-07-07 14:51 UTC, tux2000 commented
@elahd, to what i understand @TheBestMoshe already made this change in https://github.com/TheBestMoshe/home-assistant-addons/pull/20/commits/c89a089823572783f5c483bef6b9b7ea6b08ec7f

I also started a fork of this repository at https://github.com/tux2000/home-assistant-addons/ that currently is on paperless-ngx v1.7.1

2022-07-07 14:54 UTC, TheBestMoshe commented
@tux2000 I didn't realize I pushed the change to this branch 🤦‍♂️

2022-07-07 14:54 UTC, merged